
package com.hrt.gmms.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IGmmsService", targetNamespace = "http://webservice.gmms.hrt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IGmmsService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveAgentInfo", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.SaveAgentInfo")
    @ResponseWrapper(localName = "saveAgentInfoResponse", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.SaveAgentInfoResponse")
    public Boolean saveAgentInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        AgentUnitInfo arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateMerchantInfo", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.UpdateMerchantInfo")
    @ResponseWrapper(localName = "updateMerchantInfoResponse", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.UpdateMerchantInfoResponse")
    public Boolean updateMerchantInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        MerchantInfo arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveMerchantInfo", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.SaveMerchantInfo")
    @ResponseWrapper(localName = "saveMerchantInfoResponse", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.SaveMerchantInfoResponse")
    public Boolean saveMerchantInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        MerchantInfo arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "realQuery", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.RealQuery")
    @ResponseWrapper(localName = "realQueryResponse", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.RealQueryResponse")
    public String realQuery(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveTermAcc", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.SaveTermAcc")
    @ResponseWrapper(localName = "saveTermAccResponse", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.SaveTermAccResponse")
    public Boolean saveTermAcc(
        @WebParam(name = "arg0", targetNamespace = "")
        TermAcc arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveTermAccSub", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.SaveTermAccSub")
    @ResponseWrapper(localName = "saveTermAccSubResponse", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.SaveTermAccSubResponse")
    public Boolean saveTermAccSub(
        @WebParam(name = "arg0", targetNamespace = "")
        TermAcc arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);
    
    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveAggPayTermSub", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.SaveAggPayTermSub")
    @ResponseWrapper(localName = "saveAggPayTermSubResponse", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.SaveAggPayTermSubResponse")
    public Boolean saveAggPayTermSub(
    		@WebParam(name = "arg0", targetNamespace = "")
    		AggPayTerm arg0,
    		@WebParam(name = "arg1", targetNamespace = "")
    		String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateAgentInfo", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.UpdateAgentInfo")
    @ResponseWrapper(localName = "updateAgentInfoResponse", targetNamespace = "http://webservice.gmms.hrt.com/", className = "com.hrt.gmms.webservice.UpdateAgentInfoResponse")
    public Boolean updateAgentInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        AgentUnitInfo arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);
}
