package com.xwf.cloudauth.api.uid;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-04-11T11:41:16.404+08:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "UserIdentityApiServiceImplService", 
                  wsdlLocation = "file:/D:/svn/xwfproject/trunk/xwf-demo/src/main/resources/UidApiService.wsdl",
                  targetNamespace = "http://api.cloudauth.xwf.com/uid") 
public class UserIdentityApiServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://api.cloudauth.xwf.com/uid", "UserIdentityApiServiceImplService");
    public final static QName UserIdentityApiServiceImplPort = new QName("http://api.cloudauth.xwf.com/uid", "UserIdentityApiServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/svn/xwfproject/trunk/xwf-demo/src/main/resources/UidApiService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserIdentityApiServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/svn/xwfproject/trunk/xwf-demo/src/main/resources/UidApiService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserIdentityApiServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserIdentityApiServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserIdentityApiServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserIdentityApiServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    public UserIdentityApiServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public UserIdentityApiServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }    




    /**
     *
     * @return
     *     returns UserIdentityApiService
     */
    @WebEndpoint(name = "UserIdentityApiServiceImplPort")
    public UserIdentityApiService getUserIdentityApiServiceImplPort() {
        return super.getPort(UserIdentityApiServiceImplPort, UserIdentityApiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserIdentityApiService
     */
    @WebEndpoint(name = "UserIdentityApiServiceImplPort")
    public UserIdentityApiService getUserIdentityApiServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UserIdentityApiServiceImplPort, UserIdentityApiService.class, features);
    }

}
