
package com.xwf.cloudauth.api.uid;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-04-11T11:41:16.392+08:00
 * Generated source version: 3.1.3
 * 
 */
public final class UserIdentityApiService_UserIdentityApiServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://api.cloudauth.xwf.com/uid", "UserIdentityApiServiceImplService");

    private UserIdentityApiService_UserIdentityApiServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UserIdentityApiServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserIdentityApiServiceImplService ss = new UserIdentityApiServiceImplService(wsdlURL, SERVICE_NAME);
        UserIdentityApiService port = ss.getUserIdentityApiServiceImplPort();  
        
        {
        System.out.println("Invoking queryBankcardBin...");
        com.xwf.cloudauth.api.uid.QueryBankcardBinRequest _queryBankcardBin_queryBankcardBinRequest = null;
        com.xwf.cloudauth.api.uid.QueryBankcardBinResponse _queryBankcardBin__return = port.queryBankcardBin(_queryBankcardBin_queryBankcardBinRequest);
        System.out.println("queryBankcardBin.result=" + _queryBankcardBin__return);


        }
        {
        System.out.println("Invoking authenticateCard...");
        com.xwf.cloudauth.api.uid.AuthenticateCardRequest _authenticateCard_authenticateCardRequest = null;
        com.xwf.cloudauth.api.uid.AuthenticateCardResponse _authenticateCard__return = port.authenticateCard(_authenticateCard_authenticateCardRequest);
        System.out.println("authenticateCard.result=" + _authenticateCard__return);


        }
        {
        System.out.println("Invoking authCardWithoutOTP...");
        com.xwf.cloudauth.api.uid.AuthCardWithoutOTPRequest _authCardWithoutOTP_authCardWithoutOTPRequest = null;
        com.xwf.cloudauth.api.uid.AuthCardWithoutOTPResponse _authCardWithoutOTP__return = port.authCardWithoutOTP(_authCardWithoutOTP_authCardWithoutOTPRequest);
        System.out.println("authCardWithoutOTP.result=" + _authCardWithoutOTP__return);


        }
        {
        System.out.println("Invoking matchIdentityWithPhoto...");
        com.xwf.cloudauth.api.uid.MatchIdentityWithPhotoRequest _matchIdentityWithPhoto_matchIdentityWithPhotoRequest = null;
        com.xwf.cloudauth.api.uid.MatchIdentityWithPhotoResponse _matchIdentityWithPhoto__return = port.matchIdentityWithPhoto(_matchIdentityWithPhoto_matchIdentityWithPhotoRequest);
        System.out.println("matchIdentityWithPhoto.result=" + _matchIdentityWithPhoto__return);


        }
        {
        System.out.println("Invoking matchTwoPhotos...");
        com.xwf.cloudauth.api.uid.MatchTwoPhotosRequest _matchTwoPhotos_matchTwoPhotosRequest = null;
        com.xwf.cloudauth.api.uid.MatchIdentityWithPhotoResponse _matchTwoPhotos__return = port.matchTwoPhotos(_matchTwoPhotos_matchTwoPhotosRequest);
        System.out.println("matchTwoPhotos.result=" + _matchTwoPhotos__return);


        }
        {
        System.out.println("Invoking matchIdentity...");
        com.xwf.cloudauth.api.uid.MatchIdentityRequest _matchIdentity_matchIdentityRequest = null;
        com.xwf.cloudauth.api.uid.MatchIdentityResponse _matchIdentity__return = port.matchIdentity(_matchIdentity_matchIdentityRequest);
        System.out.println("matchIdentity.result=" + _matchIdentity__return);


        }
        {
        System.out.println("Invoking matchIdentityWithLivePhoto...");
        com.xwf.cloudauth.api.uid.MatchIdentityWithPhotoRequest _matchIdentityWithLivePhoto_matchIdentityWithPhotoRequest = null;
        com.xwf.cloudauth.api.uid.MatchIdentityWithPhotoResponse _matchIdentityWithLivePhoto__return = port.matchIdentityWithLivePhoto(_matchIdentityWithLivePhoto_matchIdentityWithPhotoRequest);
        System.out.println("matchIdentityWithLivePhoto.result=" + _matchIdentityWithLivePhoto__return);


        }
        {
        System.out.println("Invoking matchIdentityReturnPhoto...");
        com.xwf.cloudauth.api.uid.MatchIdentityRequest _matchIdentityReturnPhoto_matchIdentityRequest = null;
        com.xwf.cloudauth.api.uid.MatchIdentityReturnPhotoResponse _matchIdentityReturnPhoto__return = port.matchIdentityReturnPhoto(_matchIdentityReturnPhoto_matchIdentityRequest);
        System.out.println("matchIdentityReturnPhoto.result=" + _matchIdentityReturnPhoto__return);


        }
        {
        System.out.println("Invoking verifyCardOtp...");
        com.xwf.cloudauth.api.uid.VerifyCardOtpRequest _verifyCardOtp_verifyCardOtpRequest = null;
        com.xwf.cloudauth.api.uid.VerifyCardOtpResponse _verifyCardOtp__return = port.verifyCardOtp(_verifyCardOtp_verifyCardOtpRequest);
        System.out.println("verifyCardOtp.result=" + _verifyCardOtp__return);


        }

        System.exit(0);
    }

}
