package com.xwf.cloudauth.api.uid;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-04-11T11:41:16.399+08:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://api.cloudauth.xwf.com/uid", name = "UserIdentityApiService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UserIdentityApiService {

    @WebMethod(action = "http://api.cloudauth.xwf.com/uid/queryBankcardBin")
    @WebResult(name = "queryBankcardBinResponse", targetNamespace = "http://api.cloudauth.xwf.com/uid", partName = "queryBankcardBinResponse")
    public QueryBankcardBinResponse queryBankcardBin(
        @WebParam(partName = "queryBankcardBinRequest", name = "queryBankcardBinRequest", targetNamespace = "http://api.cloudauth.xwf.com/uid")
        QueryBankcardBinRequest queryBankcardBinRequest
    );

    @WebMethod(action = "http://api.cloudauth.xwf.com/uid/authenticateCard")
    @WebResult(name = "authenticateCardResponse", targetNamespace = "http://api.cloudauth.xwf.com/uid", partName = "authenticateCardResponse")
    public AuthenticateCardResponse authenticateCard(
        @WebParam(partName = "authenticateCardRequest", name = "authenticateCardRequest", targetNamespace = "http://api.cloudauth.xwf.com/uid")
        AuthenticateCardRequest authenticateCardRequest
    );

    @WebMethod(action = "http://api.cloudauth.xwf.com/uid/authCardWithoutOTP")
    @WebResult(name = "authCardWithoutOTPResponse", targetNamespace = "http://api.cloudauth.xwf.com/uid", partName = "authCardWithoutOTPResponse")
    public AuthCardWithoutOTPResponse authCardWithoutOTP(
        @WebParam(partName = "authCardWithoutOTPRequest", name = "authCardWithoutOTPRequest", targetNamespace = "http://api.cloudauth.xwf.com/uid")
        AuthCardWithoutOTPRequest authCardWithoutOTPRequest
    );

    @WebMethod(action = "http://api.cloudauth.xwf.com/uid/matchIdentityWithPhoto")
    @WebResult(name = "matchIdentityWithPhotoResponse", targetNamespace = "http://api.cloudauth.xwf.com/uid", partName = "matchIdentityWithPhotoResponse")
    public MatchIdentityWithPhotoResponse matchIdentityWithPhoto(
        @WebParam(partName = "matchIdentityWithPhotoRequest", name = "matchIdentityWithPhotoRequest", targetNamespace = "http://api.cloudauth.xwf.com/uid")
        MatchIdentityWithPhotoRequest matchIdentityWithPhotoRequest
    );

    @WebMethod(action = "http://api.cloudauth.xwf.com/uid/matchTwoPhotos")
    @WebResult(name = "matchTwoPhotosResponse", targetNamespace = "http://api.cloudauth.xwf.com/uid", partName = "matchIdentityWithPhotoResponse")
    public MatchIdentityWithPhotoResponse matchTwoPhotos(
        @WebParam(partName = "matchTwoPhotosRequest", name = "matchTwoPhotosRequest", targetNamespace = "http://api.cloudauth.xwf.com/uid")
        MatchTwoPhotosRequest matchTwoPhotosRequest
    );

    @WebMethod(action = "http://api.cloudauth.xwf.com/uid/matchIdentity")
    @WebResult(name = "matchIdentityResponse", targetNamespace = "http://api.cloudauth.xwf.com/uid", partName = "matchIdentityResponse")
    public MatchIdentityResponse matchIdentity(
        @WebParam(partName = "matchIdentityRequest", name = "matchIdentityRequest", targetNamespace = "http://api.cloudauth.xwf.com/uid")
        MatchIdentityRequest matchIdentityRequest
    );

    @WebMethod(action = "http://api.cloudauth.xwf.com/uid/matchIdentityWithLivePhoto")
    @WebResult(name = "matchIdentityWithLivePhotoResponse", targetNamespace = "http://api.cloudauth.xwf.com/uid", partName = "matchIdentityWithPhotoResponse")
    public MatchIdentityWithPhotoResponse matchIdentityWithLivePhoto(
        @WebParam(partName = "matchIdentityWithPhotoRequest", name = "matchIdentityWithLivePhotoRequest", targetNamespace = "http://api.cloudauth.xwf.com/uid")
        MatchIdentityWithPhotoRequest matchIdentityWithPhotoRequest
    );

    @WebMethod(action = "http://api.cloudauth.xwf.com/uid/matchIdentityReturnPhoto")
    @WebResult(name = "matchIdentityReturnPhotoResponse", targetNamespace = "http://api.cloudauth.xwf.com/uid", partName = "matchIdentityReturnPhotoResponse")
    public MatchIdentityReturnPhotoResponse matchIdentityReturnPhoto(
        @WebParam(partName = "matchIdentityRequest", name = "matchIdentityReturnPhotoRequest", targetNamespace = "http://api.cloudauth.xwf.com/uid")
        MatchIdentityRequest matchIdentityRequest
    );

    @WebMethod(action = "http://api.cloudauth.xwf.com/uid/verifyCardOtp")
    @WebResult(name = "verifyCardOtpResponse", targetNamespace = "http://api.cloudauth.xwf.com/uid", partName = "verifyCardOtpResponse")
    public VerifyCardOtpResponse verifyCardOtp(
        @WebParam(partName = "verifyCardOtpRequest", name = "verifyCardOtpRequest", targetNamespace = "http://api.cloudauth.xwf.com/uid")
        VerifyCardOtpRequest verifyCardOtpRequest
    );
}
